export interface LanguageOption {
  /** BCP-47 tag, e.g. "es-ES" */
  code: string;
  /** Human-friendly name, e.g. "Spanish (Spain)" */
  label: string;
}

/**
 * Every language with official or national status in a sovereign state,
 * plus common regional variants that matter for TTS voice matching.
 */
export const LANGUAGES: LanguageOption[] = [
  { code: 'ab', label: 'Abkhaz' },
  { code: 'af', label: 'Afrikaans' },
  { code: 'ak', label: 'Akan (Twi)' },
  { code: 'am', label: 'Amharic' },
  { code: 'ar', label: 'Arabic' },
  { code: 'ar-AE', label: 'Arabic (UAE)' },
  { code: 'ar-EG', label: 'Arabic (Egypt)' },
  { code: 'ar-BH', label: 'Arabic (Bahrain)' },
  { code: 'ar-DZ', label: 'Arabic (Algeria)' },
  { code: 'ar-KW', label: 'Arabic (Kuwait)' },
  { code: 'ar-LY', label: 'Arabic (Libya)' },
  { code: 'ar-OM', label: 'Arabic (Oman)' },
  { code: 'ar-PS', label: 'Arabic (Palestine)' },
  { code: 'ar-QA', label: 'Arabic (Qatar)' },
  { code: 'ar-YE', label: 'Arabic (Yemen)' },
  { code: 'ar-IQ', label: 'Arabic (Iraq)' },
  { code: 'ar-JO', label: 'Arabic (Jordan)' },
  { code: 'ar-LB', label: 'Arabic (Lebanon)' },
  { code: 'ar-MA', label: 'Arabic (Morocco)' },
  { code: 'ar-SA', label: 'Arabic (Saudi Arabia)' },
  { code: 'ar-SD', label: 'Arabic (Sudan)' },
  { code: 'ar-SY', label: 'Arabic (Syria)' },
  { code: 'ar-TN', label: 'Arabic (Tunisia)' },
  { code: 'as', label: 'Assamese' },
  { code: 'ay', label: 'Aymara' },
  { code: 'az', label: 'Azerbaijani' },
  { code: 'bal', label: 'Balochi' },
  { code: 'bem', label: 'Bemba' },
  { code: 'be', label: 'Belarusian' },
  { code: 'bg', label: 'Bulgarian' },
  { code: 'bi', label: 'Bislama' },
  { code: 'bm', label: 'Bambara' },
  { code: 'bn', label: 'Bangla (Bengali)' },
  { code: 'bo', label: 'Tibetan' },
  { code: 'brx', label: 'Bodo' },
  { code: 'bs', label: 'Bosnian' },
  { code: 'ca', label: 'Catalan' },
  { code: 'ceb', label: 'Cebuano' },
  { code: 'ckb', label: 'Kurdish (Sorani)' },
  { code: 'cnr', label: 'Montenegrin' },
  { code: 'crs', label: 'Seychellois Creole' },
  { code: 'cs', label: 'Czech' },
  { code: 'cy', label: 'Welsh' },
  { code: 'da', label: 'Danish' },
  { code: 'de-AT', label: 'German (Austria)' },
  { code: 'de-CH', label: 'German (Switzerland)' },
  { code: 'de-DE', label: 'German (Germany)' },
  { code: 'dje', label: 'Zarma' },
  { code: 'din', label: 'Dinka' },
  { code: 'doi', label: 'Dogri' },
  { code: 'dv', label: 'Dhivehi' },
  { code: 'dz', label: 'Dzongkha' },
  { code: 'ee', label: 'Ewe' },
  { code: 'en', label: 'English' },
  { code: 'en-AU', label: 'English (Australia)' },
  { code: 'en-CA', label: 'English (Canada)' },
  { code: 'en-GB', label: 'English (UK)' },
  { code: 'en-IE', label: 'English (Ireland)' },
  { code: 'en-IN', label: 'English (India)' },
  { code: 'en-NZ', label: 'English (New Zealand)' },
  { code: 'en-US', label: 'English (US)' },
  { code: 'en-ZA', label: 'English (South Africa)' },
  { code: 'eo', label: 'Esperanto' },
  { code: 'es-419', label: 'Spanish (Latin America)' },
  { code: 'es-AR', label: 'Spanish (Argentina)' },
  { code: 'es-BO', label: 'Spanish (Bolivia)' },
  { code: 'es-CL', label: 'Spanish (Chile)' },
  { code: 'es-CO', label: 'Spanish (Colombia)' },
  { code: 'es-CR', label: 'Spanish (Costa Rica)' },
  { code: 'es-NI', label: 'Spanish (Nicaragua)' },
  { code: 'es-PA', label: 'Spanish (Panama)' },
  { code: 'es-PR', label: 'Spanish (Puerto Rico)' },
  { code: 'es-CU', label: 'Spanish (Cuba)' },
  { code: 'es-DO', label: 'Spanish (Dominican Republic)' },
  { code: 'es-EC', label: 'Spanish (Ecuador)' },
  { code: 'es-ES', label: 'Spanish (Spain)' },
  { code: 'es-GT', label: 'Spanish (Guatemala)' },
  { code: 'es-HN', label: 'Spanish (Honduras)' },
  { code: 'es-MX', label: 'Spanish (Mexico)' },
  { code: 'es-PE', label: 'Spanish (Peru)' },
  { code: 'es-PY', label: 'Spanish (Paraguay)' },
  { code: 'es-SV', label: 'Spanish (El Salvador)' },
  { code: 'es-UY', label: 'Spanish (Uruguay)' },
  { code: 'es-VE', label: 'Spanish (Venezuela)' },
  { code: 'et', label: 'Estonian' },
  { code: 'eu', label: 'Basque' },
  { code: 'fa', label: 'Persian (Farsi)' },
  { code: 'fa-AF', label: 'Dari (Afghan Persian)' },
  { code: 'ff', label: 'Fula (Pulaar)' },
  { code: 'fi', label: 'Finnish' },
  { code: 'fil', label: 'Filipino' },
  { code: 'fj', label: 'Fijian' },
  { code: 'fo', label: 'Faroese' },
  { code: 'fr-BE', label: 'French (Belgium)' },
  { code: 'fr-CA', label: 'French (Canada)' },
  { code: 'fr-CH', label: 'French (Switzerland)' },
  { code: 'fr-FR', label: 'French (France)' },
  { code: 'fr-LU', label: 'French (Luxembourg)' },
  { code: 'fy', label: 'Frisian (Western)' },
  { code: 'ga', label: 'Irish' },
  { code: 'gd', label: 'Scottish Gaelic' },
  { code: 'gil', label: 'Gilbertese' },
  { code: 'gl', label: 'Galician' },
  { code: 'gn', label: 'Guaraní' },
  { code: 'gu', label: 'Gujarati' },
  { code: 'ha', label: 'Hausa' },
  { code: 'haw', label: 'Hawaiian' },
  { code: 'he', label: 'Hebrew' },
  { code: 'hi', label: 'Hindi' },
  { code: 'hif', label: 'Fiji Hindi' },
  { code: 'ho', label: 'Hiri Motu' },
  { code: 'hr', label: 'Croatian' },
  { code: 'ht', label: 'Haitian Creole' },
  { code: 'hu', label: 'Hungarian' },
  { code: 'hy', label: 'Armenian' },
  { code: 'id', label: 'Indonesian' },
  { code: 'ig', label: 'Igbo' },
  { code: 'is', label: 'Icelandic' },
  { code: 'it', label: 'Italian' },
  { code: 'it-CH', label: 'Italian (Switzerland)' },
  { code: 'iu', label: 'Inuktitut' },
  { code: 'ja', label: 'Japanese' },
  { code: 'ja-JP', label: 'Japanese (Japan)' },
  { code: 'jv', label: 'Javanese' },
  { code: 'ka', label: 'Georgian' },
  { code: 'kbp', label: 'Kabiye' },
  { code: 'kck', label: 'Kalanga' },
  { code: 'kea', label: 'Cape Verdean Creole' },
  { code: 'kg', label: 'Kikongo' },
  { code: 'kk', label: 'Kazakh' },
  { code: 'kl', label: 'Greenlandic' },
  { code: 'km', label: 'Khmer' },
  { code: 'kmr', label: 'Kurdish (Kurmanji)' },
  { code: 'kn', label: 'Kannada' },
  { code: 'ko', label: 'Korean' },
  { code: 'ko-KR', label: 'Korean (South Korea)' },
  { code: 'kok', label: 'Konkani' },
  { code: 'kri', label: 'Krio' },
  { code: 'ks', label: 'Kashmiri' },
  { code: 'ktu', label: 'Kituba' },
  { code: 'ku', label: 'Kurdish' },
  { code: 'kw', label: 'Cornish' },
  { code: 'ky', label: 'Kyrgyz' },
  { code: 'la', label: 'Latin' },
  { code: 'lb', label: 'Luxembourgish' },
  { code: 'ln', label: 'Lingala' },
  { code: 'lo', label: 'Lao' },
  { code: 'loz', label: 'Lozi' },
  { code: 'lt', label: 'Lithuanian' },
  { code: 'lua', label: 'Tshiluba' },
  { code: 'lue', label: 'Luvale' },
  { code: 'lun', label: 'Lunda' },
  { code: 'lv', label: 'Latvian' },
  { code: 'mai', label: 'Maithili' },
  { code: 'mfe', label: 'Mauritian Creole' },
  { code: 'mg', label: 'Malagasy' },
  { code: 'mh', label: 'Marshallese' },
  { code: 'mi', label: 'Māori' },
  { code: 'mk', label: 'Macedonian' },
  { code: 'ml', label: 'Malayalam' },
  { code: 'mn', label: 'Mongolian' },
  { code: 'mni', label: 'Meitei (Manipuri)' },
  { code: 'mr', label: 'Marathi' },
  { code: 'ms', label: 'Malay' },
  { code: 'mt', label: 'Maltese' },
  { code: 'my', label: 'Burmese' },
  { code: 'na', label: 'Nauruan' },
  { code: 'nah', label: 'Nahuatl' },
  { code: 'nb-NO', label: 'Norwegian (Bokmål)' },
  { code: 'nd', label: 'Ndebele' },
  { code: 'ndc', label: 'Ndau' },
  { code: 'ne', label: 'Nepali' },
  { code: 'nl', label: 'Dutch' },
  { code: 'nl-BE', label: 'Dutch (Belgium)' },
  { code: 'nn-NO', label: 'Norwegian (Nynorsk)' },
  { code: 'no', label: 'Norwegian' },
  { code: 'nso', label: 'Sepedi (Northern Sotho)' },
  { code: 'ny', label: 'Chichewa (Nyanja)' },
  { code: 'oc', label: 'Occitan (Aranese)' },
  { code: 'om', label: 'Oromo' },
  { code: 'or', label: 'Odia' },
  { code: 'pa', label: 'Punjabi' },
  { code: 'pap', label: 'Papiamento' },
  { code: 'pau', label: 'Palauan' },
  { code: 'pl', label: 'Polish' },
  { code: 'ps', label: 'Pashto' },
  { code: 'pt-AO', label: 'Portuguese (Angola)' },
  { code: 'pt-BR', label: 'Portuguese (Brazil)' },
  { code: 'pt-MZ', label: 'Portuguese (Mozambique)' },
  { code: 'pt-CV', label: 'Portuguese (Cape Verde)' },
  { code: 'pt-GW', label: 'Portuguese (Guinea-Bissau)' },
  { code: 'pt-ST', label: 'Portuguese (São Tomé and Príncipe)' },
  { code: 'pt-TL', label: 'Portuguese (Timor-Leste)' },
  { code: 'pt-PT', label: 'Portuguese (Portugal)' },
  { code: 'qu', label: 'Quechua' },
  { code: 'quc', label: "K'iche'" },
  { code: 'rn', label: 'Kirundi' },
  { code: 'ro', label: 'Romanian' },
  { code: 'rm', label: 'Romansh' },
  { code: 'ru', label: 'Russian' },
  { code: 'rw', label: 'Kinyarwanda' },
  { code: 'sa', label: 'Sanskrit' },
  { code: 'sat', label: 'Santali' },
  { code: 'sd', label: 'Sindhi' },
  { code: 'se', label: 'Sami (Northern)' },
  { code: 'sg', label: 'Sango' },
  { code: 'si', label: 'Sinhala' },
  { code: 'sk', label: 'Slovak' },
  { code: 'sl', label: 'Slovenian' },
  { code: 'sm', label: 'Samoan' },
  { code: 'sn', label: 'Shona' },
  { code: 'so', label: 'Somali' },
  { code: 'sq', label: 'Albanian' },
  { code: 'sr', label: 'Serbian' },
  { code: 'ss', label: 'Swati (siSwati)' },
  { code: 'st', label: 'Sesotho (Southern Sotho)' },
  { code: 'sv', label: 'Swedish' },
  { code: 'sw', label: 'Swahili' },
  { code: 'swb', label: 'Comorian' },
  { code: 'ta', label: 'Tamil' },
  { code: 'te', label: 'Telugu' },
  { code: 'tet', label: 'Tetum' },
  { code: 'tg', label: 'Tajik' },
  { code: 'th', label: 'Thai' },
  { code: 'ti', label: 'Tigrinya' },
  { code: 'tk', label: 'Turkmen' },
  { code: 'tn', label: 'Setswana (Tswana)' },
  { code: 'to', label: 'Tongan' },
  { code: 'toi', label: 'Tonga (Zambia)' },
  { code: 'tpi', label: 'Tok Pisin' },
  { code: 'tr', label: 'Turkish' },
  { code: 'ts', label: 'Tsonga (Xitsonga)' },
  { code: 'tt', label: 'Tatar' },
  { code: 'tvl', label: 'Tuvaluan' },
  { code: 'ty', label: 'Tahitian' },
  { code: 'ug', label: 'Uyghur' },
  { code: 'uk', label: 'Ukrainian' },
  { code: 'ur', label: 'Urdu' },
  { code: 'uz', label: 'Uzbek' },
  { code: 've', label: 'Venda (Tshivenda)' },
  { code: 'vi', label: 'Vietnamese' },
  { code: 'wo', label: 'Wolof' },
  { code: 'xh', label: 'Xhosa' },
  { code: 'yi', label: 'Yiddish' },
  { code: 'yo', label: 'Yoruba' },
  { code: 'za', label: 'Zhuang' },
  { code: 'zgh', label: 'Tamazight (Standard Moroccan Berber)' },
  { code: 'zh', label: 'Chinese' },
  { code: 'zh-CN', label: 'Chinese (Simplified)' },
  { code: 'zh-HK', label: 'Chinese (Hong Kong)' },
  { code: 'zh-SG', label: 'Chinese (Singapore)' },
  { code: 'zh-TW', label: 'Chinese (Traditional)' },
  { code: 'zu', label: 'Zulu' },
];

const BY_CODE = new Map(LANGUAGES.map((l) => [l.code.toLowerCase(), l]));

/** Friendly name for a BCP-47 code, or undefined if unknown. */
export function findLanguage(code: string): LanguageOption | undefined {
  const c = code.trim().toLowerCase();
  const exact = BY_CODE.get(c);
  if (exact) return exact;
  // Fall back to the base language tag, e.g. "ja-JP" -> "ja", "zh-Hans" -> "zh"
  const base = c.split('-')[0];
  return BY_CODE.get(base);
}
