import type { VocabSet, VocabWord } from '@/types/app';
import { PACK_LANG } from '@/lib/starterSets';
import { loadWordBank } from '@/lib/vocab/wordBanks';

// Expanded starter sets (20-25 words each) generated from the A1/A2 travel-
// essentials template, hand-checked per language. Replaces the original 5-word
// demo sets so every dashboard card carries a real vocabulary list.

/**
 * Pull the full A1 word pack for a seed set's language when one exists, so the
 * home-screen card reflects the real dataset (200+ words) instead of the small
 * curated demo array.
 *
 * `hydrated` is false when the language HAS a pack but it could not be loaded
 * (offline / fetch error). In that case the curated words are used as a
 * fallback — the caller decides whether to mark hydration incomplete so a
 * later launch can retry.
 */
export async function hydrateSeedWords(set: VocabSet): Promise<{ words: VocabWord[]; hydrated: boolean }> {
  const pack = PACK_LANG[set.lang];
  if (!pack) return { words: set.words, hydrated: true }; // nothing to hydrate
  try {
    const bank = await loadWordBank(pack, 'A1');
    if (bank && bank.words.length > 0) {
      return {
        words: bank.words.map(([target, translation], i) => ({
          id: `pk-${pack}-a1-${i}`,
          target,
          translation,
        })),
        hydrated: true,
      };
    }
  } catch {
    /* offline / pack unavailable: fall back below */
  }
  return { words: set.words, hydrated: false };
}

/**
 * The starter set for a normalized pack-level language key (e.g. "es" → the
 * Spanish seed, "mn" → the Mongolian seed), or null when the language has no
 * seed content. Seedable languages are exactly those with a seed set.
 */
export function seedSetForLang(langKey: string): VocabSet | null {
  const key = langKey.toLowerCase();
  return SEED_SETS.find((s) => (PACK_LANG[s.lang] ?? s.lang).toLowerCase() === key) ?? null;
}

export const SEED_SETS: VocabSet[] = [
  {
    id: 'seed-spanish-essentials',
    name: 'Spanish Essentials',
    lang: 'es-ES',
    nativeLang: 'en-US',
    cefr: 'A1',
    words: [
      { id: 'w-hola', target: 'hola', translation: 'hello' },
      { id: 'w-gracias', target: 'gracias', translation: 'thank you' },
      { id: 'w-por-favor', target: 'por favor', translation: 'please', repeats: 3 },
      { id: 'w-lo-siento', target: 'lo siento', translation: 'I am sorry' },
      { id: 'w-adios', target: 'adiós', translation: 'goodbye' },
      { id: 'w-spanish-essentials-5', target: 'sí', translation: 'yes' },
      { id: 'w-spanish-essentials-6', target: 'no', translation: 'no' },
      { id: 'w-spanish-essentials-7', target: 'agua', translation: 'water' },
      { id: 'w-spanish-essentials-8', target: 'pan', translation: 'bread' },
      { id: 'w-spanish-essentials-9', target: 'familia', translation: 'family' },
      { id: 'w-spanish-essentials-10', target: 'amigo', translation: 'friend' },
      { id: 'w-spanish-essentials-11', target: 'estación', translation: 'station' },
      { id: 'w-spanish-essentials-12', target: 'billete', translation: 'ticket' },
      { id: 'w-spanish-essentials-13', target: 'calle', translation: 'street' },
      { id: 'w-spanish-essentials-14', target: 'izquierda', translation: 'left' },
      { id: 'w-spanish-essentials-15', target: 'derecha', translation: 'right' },
      { id: 'w-spanish-essentials-16', target: '¿cuánto cuesta?', translation: 'how much?' },
      { id: 'w-spanish-essentials-17', target: 'tienda', translation: 'shop' },
      { id: 'w-spanish-essentials-18', target: 'hotel', translation: 'hotel' },
      { id: 'w-spanish-essentials-19', target: 'mañana', translation: 'morning' },
      { id: 'w-spanish-essentials-20', target: 'tarde', translation: 'evening' },
    ],
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'seed-french-basics',
    name: 'French Basics',
    lang: 'fr-FR',
    nativeLang: 'en-US',
    cefr: 'A1',
    words: [
      { id: 'w-bonjour', target: 'bonjour', translation: 'hello / good morning' },
      { id: 'w-merci', target: 'merci', translation: 'thank you' },
      { id: 'w-oui', target: 'oui', translation: 'yes' },
      { id: 'w-non', target: 'non', translation: 'no' },
      { id: 'w-ou-est', target: 'où est la gare ?', translation: 'where is the station?' },
      { id: 'w-french-basics-5', target: 's\'il vous plaît', translation: 'please' },
      { id: 'w-french-basics-6', target: 'au revoir', translation: 'goodbye' },
      { id: 'w-french-basics-7', target: 'eau', translation: 'water' },
      { id: 'w-french-basics-8', target: 'pain', translation: 'bread' },
      { id: 'w-french-basics-9', target: 'famille', translation: 'family' },
      { id: 'w-french-basics-10', target: 'ami', translation: 'friend' },
      { id: 'w-french-basics-11', target: 'gare', translation: 'station' },
      { id: 'w-french-basics-12', target: 'billet', translation: 'ticket' },
      { id: 'w-french-basics-13', target: 'rue', translation: 'street' },
      { id: 'w-french-basics-14', target: 'gauche', translation: 'left' },
      { id: 'w-french-basics-15', target: 'droite', translation: 'right' },
      { id: 'w-french-basics-16', target: 'combien ça coûte ?', translation: 'how much?' },
      { id: 'w-french-basics-17', target: 'magasin', translation: 'shop' },
      { id: 'w-french-basics-18', target: 'hôtel', translation: 'hotel' },
      { id: 'w-french-basics-19', target: 'matin', translation: 'morning' },
      { id: 'w-french-basics-20', target: 'soir', translation: 'evening' },
    ],
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'seed-german-phrases',
    name: 'German Phrases',
    lang: 'de-DE',
    nativeLang: 'en-US',
    cefr: 'A1',
    words: [
      { id: 'w-hallo', target: 'hallo', translation: 'hello' },
      { id: 'w-danke', target: 'danke', translation: 'thank you' },
      { id: 'w-bitte', target: 'bitte', translation: 'please / you are welcome' },
      { id: 'w-entschuldigung', target: 'Entschuldigung', translation: 'excuse me / sorry' },
      { id: 'w-wo-ist', target: 'Wo ist die Toilette?', translation: 'where is the toilet?', repeats: 3 },
      { id: 'w-german-phrases-5', target: 'auf Wiedersehen', translation: 'goodbye' },
      { id: 'w-german-phrases-6', target: 'ja', translation: 'yes' },
      { id: 'w-german-phrases-7', target: 'nein', translation: 'no' },
      { id: 'w-german-phrases-8', target: 'Wasser', translation: 'water' },
      { id: 'w-german-phrases-9', target: 'Brot', translation: 'bread' },
      { id: 'w-german-phrases-10', target: 'Familie', translation: 'family' },
      { id: 'w-german-phrases-11', target: 'Freund', translation: 'friend' },
      { id: 'w-german-phrases-12', target: 'Bahnhof', translation: 'station' },
      { id: 'w-german-phrases-13', target: 'Fahrkarte', translation: 'ticket' },
      { id: 'w-german-phrases-14', target: 'Straße', translation: 'street' },
      { id: 'w-german-phrases-15', target: 'links', translation: 'left' },
      { id: 'w-german-phrases-16', target: 'rechts', translation: 'right' },
      { id: 'w-german-phrases-17', target: 'wie viel kostet das?', translation: 'how much?' },
      { id: 'w-german-phrases-18', target: 'Geschäft', translation: 'shop' },
      { id: 'w-german-phrases-19', target: 'Hotel', translation: 'hotel' },
      { id: 'w-german-phrases-20', target: 'Morgen', translation: 'morning' },
      { id: 'w-german-phrases-21', target: 'Abend', translation: 'evening' },
    ],
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'seed-japanese-greetings',
    name: 'Japanese Greetings',
    lang: 'ja-JP',
    nativeLang: 'en-US',
    cefr: 'A1',
    words: [
      { id: 'w-konnichiwa', target: 'こんにちは', translation: 'hello' },
      { id: 'w-arigatou', target: 'ありがとう', translation: 'thank you' },
      { id: 'w-sumimasen', target: 'すみません', translation: 'excuse me / sorry' },
      { id: 'w-hai', target: 'はい', translation: 'yes' },
      { id: 'w-ie', target: 'いいえ', translation: 'no' },
      { id: 'w-japanese-greetings-5', target: 'お願いします', translation: 'please' },
      { id: 'w-japanese-greetings-6', target: 'さようなら', translation: 'goodbye' },
      { id: 'w-japanese-greetings-7', target: '水', translation: 'water' },
      { id: 'w-japanese-greetings-8', target: 'パン', translation: 'bread' },
      { id: 'w-japanese-greetings-9', target: '家族', translation: 'family' },
      { id: 'w-japanese-greetings-10', target: '友達', translation: 'friend' },
      { id: 'w-japanese-greetings-11', target: '駅', translation: 'station' },
      { id: 'w-japanese-greetings-12', target: '切符', translation: 'ticket' },
      { id: 'w-japanese-greetings-13', target: '道', translation: 'street' },
      { id: 'w-japanese-greetings-14', target: '左', translation: 'left' },
      { id: 'w-japanese-greetings-15', target: '右', translation: 'right' },
      { id: 'w-japanese-greetings-16', target: 'いくらですか？', translation: 'how much?' },
      { id: 'w-japanese-greetings-17', target: '店', translation: 'shop' },
      { id: 'w-japanese-greetings-18', target: 'ホテル', translation: 'hotel' },
      { id: 'w-japanese-greetings-19', target: '朝', translation: 'morning' },
      { id: 'w-japanese-greetings-20', target: '夜', translation: 'evening' },
    ],
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'seed-portuguese-basics',
    name: 'Portuguese Basics',
    lang: 'pt-BR',
    nativeLang: 'en-US',
    cefr: 'A1',
    words: [
      { id: 'w-pt-ola', target: 'olá', translation: 'hello' },
      { id: 'w-pt-obrigado', target: 'obrigado', translation: 'thank you' },
      { id: 'w-pt-por-favor', target: 'por favor', translation: 'please', repeats: 3 },
      { id: 'w-pt-sim', target: 'sim', translation: 'yes' },
      { id: 'w-pt-adeus', target: 'adeus', translation: 'goodbye' },
      { id: 'w-portuguese-basics-5', target: 'não', translation: 'no' },
      { id: 'w-portuguese-basics-6', target: 'água', translation: 'water' },
      { id: 'w-portuguese-basics-7', target: 'pão', translation: 'bread' },
      { id: 'w-portuguese-basics-8', target: 'família', translation: 'family' },
      { id: 'w-portuguese-basics-9', target: 'amigo', translation: 'friend' },
      { id: 'w-portuguese-basics-10', target: 'estação', translation: 'station' },
      { id: 'w-portuguese-basics-11', target: 'bilhete', translation: 'ticket' },
      { id: 'w-portuguese-basics-12', target: 'rua', translation: 'street' },
      { id: 'w-portuguese-basics-13', target: 'esquerda', translation: 'left' },
      { id: 'w-portuguese-basics-14', target: 'direita', translation: 'right' },
      { id: 'w-portuguese-basics-15', target: 'quanto custa?', translation: 'how much?' },
      { id: 'w-portuguese-basics-16', target: 'loja', translation: 'shop' },
      { id: 'w-portuguese-basics-17', target: 'hotel', translation: 'hotel' },
      { id: 'w-portuguese-basics-18', target: 'manhã', translation: 'morning' },
      { id: 'w-portuguese-basics-19', target: 'noite', translation: 'evening' },
    ],
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'seed-italian-essentials',
    name: 'Italian Essentials',
    lang: 'it',
    nativeLang: 'en-US',
    cefr: 'A1',
    words: [
      { id: 'w-it-ciao', target: 'ciao', translation: 'hello / goodbye' },
      { id: 'w-it-grazie', target: 'grazie', translation: 'thank you' },
      { id: 'w-it-per-favore', target: 'per favore', translation: 'please' },
      { id: 'w-it-si', target: 'sì', translation: 'yes' },
      { id: 'w-it-arrivederci', target: 'arrivederci', translation: 'goodbye', repeats: 3 },
      { id: 'w-italian-essentials-5', target: 'no', translation: 'no' },
      { id: 'w-italian-essentials-6', target: 'acqua', translation: 'water' },
      { id: 'w-italian-essentials-7', target: 'pane', translation: 'bread' },
      { id: 'w-italian-essentials-8', target: 'famiglia', translation: 'family' },
      { id: 'w-italian-essentials-9', target: 'amico', translation: 'friend' },
      { id: 'w-italian-essentials-10', target: 'stazione', translation: 'station' },
      { id: 'w-italian-essentials-11', target: 'biglietto', translation: 'ticket' },
      { id: 'w-italian-essentials-12', target: 'strada', translation: 'street' },
      { id: 'w-italian-essentials-13', target: 'sinistra', translation: 'left' },
      { id: 'w-italian-essentials-14', target: 'destra', translation: 'right' },
      { id: 'w-italian-essentials-15', target: 'quanto costa?', translation: 'how much?' },
      { id: 'w-italian-essentials-16', target: 'negozio', translation: 'shop' },
      { id: 'w-italian-essentials-17', target: 'albergo', translation: 'hotel' },
      { id: 'w-italian-essentials-18', target: 'mattina', translation: 'morning' },
      { id: 'w-italian-essentials-19', target: 'sera', translation: 'evening' },
    ],
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'seed-russian-basics',
    name: 'Russian Basics',
    lang: 'ru',
    nativeLang: 'en-US',
    cefr: 'A1',
    words: [
      { id: 'w-ru-privet', target: 'привет', translation: 'hello' },
      { id: 'w-ru-spasibo', target: 'спасибо', translation: 'thank you' },
      { id: 'w-ru-pozhaluysta', target: 'пожалуйста', translation: 'please / you are welcome', repeats: 3 },
      { id: 'w-ru-da', target: 'да', translation: 'yes' },
      { id: 'w-ru-do-svidaniya', target: 'до свидания', translation: 'goodbye' },
      { id: 'w-russian-basics-5', target: 'нет', translation: 'no' },
      { id: 'w-russian-basics-6', target: 'вода', translation: 'water' },
      { id: 'w-russian-basics-7', target: 'хлеб', translation: 'bread' },
      { id: 'w-russian-basics-8', target: 'семья', translation: 'family' },
      { id: 'w-russian-basics-9', target: 'друг', translation: 'friend' },
      { id: 'w-russian-basics-10', target: 'вокзал', translation: 'station' },
      { id: 'w-russian-basics-11', target: 'билет', translation: 'ticket' },
      { id: 'w-russian-basics-12', target: 'улица', translation: 'street' },
      { id: 'w-russian-basics-13', target: 'налево', translation: 'left' },
      { id: 'w-russian-basics-14', target: 'направо', translation: 'right' },
      { id: 'w-russian-basics-15', target: 'сколько стоит?', translation: 'how much?' },
      { id: 'w-russian-basics-16', target: 'магазин', translation: 'shop' },
      { id: 'w-russian-basics-17', target: 'гостиница', translation: 'hotel' },
      { id: 'w-russian-basics-18', target: 'утро', translation: 'morning' },
      { id: 'w-russian-basics-19', target: 'вечер', translation: 'evening' },
    ],
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'seed-chinese-basics',
    name: 'Chinese Basics',
    lang: 'zh-CN',
    nativeLang: 'en-US',
    cefr: 'A1',
    words: [
      { id: 'w-zh-nihao', target: '你好', translation: 'hello' },
      { id: 'w-zh-xiexie', target: '谢谢', translation: 'thank you' },
      { id: 'w-zh-qing', target: '请', translation: 'please' },
      { id: 'w-zh-shi', target: '是', translation: 'yes' },
      { id: 'w-zh-zaijian', target: '再见', translation: 'goodbye', repeats: 3 },
      { id: 'w-chinese-basics-5', target: '不', translation: 'no' },
      { id: 'w-chinese-basics-6', target: '水', translation: 'water' },
      { id: 'w-chinese-basics-7', target: '面包', translation: 'bread' },
      { id: 'w-chinese-basics-8', target: '家庭', translation: 'family' },
      { id: 'w-chinese-basics-9', target: '朋友', translation: 'friend' },
      { id: 'w-chinese-basics-10', target: '车站', translation: 'station' },
      { id: 'w-chinese-basics-11', target: '票', translation: 'ticket' },
      { id: 'w-chinese-basics-12', target: '街道', translation: 'street' },
      { id: 'w-chinese-basics-13', target: '左边', translation: 'left' },
      { id: 'w-chinese-basics-14', target: '右边', translation: 'right' },
      { id: 'w-chinese-basics-15', target: '多少钱？', translation: 'how much?' },
      { id: 'w-chinese-basics-16', target: '商店', translation: 'shop' },
      { id: 'w-chinese-basics-17', target: '酒店', translation: 'hotel' },
      { id: 'w-chinese-basics-18', target: '早上', translation: 'morning' },
      { id: 'w-chinese-basics-19', target: '晚上', translation: 'evening' },
    ],
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'seed-korean-essentials',
    name: 'Korean Essentials',
    lang: 'ko',
    nativeLang: 'en-US',
    cefr: 'A1',
    words: [
      { id: 'w-ko-annyeong', target: '안녕하세요', translation: 'hello' },
      { id: 'w-ko-gamsahamnida', target: '감사합니다', translation: 'thank you', repeats: 3 },
      { id: 'w-ko-juseyo', target: '주세요', translation: 'please (give me)' },
      { id: 'w-ko-ne', target: '네', translation: 'yes' },
      { id: 'w-ko-annyeonghi', target: '안녕히 가세요', translation: 'goodbye' },
      { id: 'w-korean-essentials-5', target: '아니요', translation: 'no' },
      { id: 'w-korean-essentials-6', target: '물', translation: 'water' },
      { id: 'w-korean-essentials-7', target: '빵', translation: 'bread' },
      { id: 'w-korean-essentials-8', target: '가족', translation: 'family' },
      { id: 'w-korean-essentials-9', target: '친구', translation: 'friend' },
      { id: 'w-korean-essentials-10', target: '역', translation: 'station' },
      { id: 'w-korean-essentials-11', target: '표', translation: 'ticket' },
      { id: 'w-korean-essentials-12', target: '길', translation: 'street' },
      { id: 'w-korean-essentials-13', target: '왼쪽', translation: 'left' },
      { id: 'w-korean-essentials-14', target: '오른쪽', translation: 'right' },
      { id: 'w-korean-essentials-15', target: '얼마예요?', translation: 'how much?' },
      { id: 'w-korean-essentials-16', target: '가게', translation: 'shop' },
      { id: 'w-korean-essentials-17', target: '호텔', translation: 'hotel' },
      { id: 'w-korean-essentials-18', target: '아침', translation: 'morning' },
      { id: 'w-korean-essentials-19', target: '저녁', translation: 'evening' },
    ],
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'seed-arabic-essentials',
    name: 'Arabic Essentials',
    lang: 'ar-EG',
    nativeLang: 'en-US',
    cefr: 'A1',
    words: [
      { id: 'w-ar-marhaba', target: 'مرحبا', translation: 'hello' },
      { id: 'w-ar-shukran', target: 'شكرا', translation: 'thank you' },
      { id: 'w-ar-min-fadlik', target: 'من فضلك', translation: 'please' },
      { id: 'w-ar-naam', target: 'نعم', translation: 'yes' },
      { id: 'w-ar-wadaan', target: 'وداعا', translation: 'goodbye', repeats: 3 },
      { id: 'w-arabic-essentials-5', target: 'لا', translation: 'no' },
      { id: 'w-arabic-essentials-6', target: 'ماء', translation: 'water' },
      { id: 'w-arabic-essentials-7', target: 'خبز', translation: 'bread' },
      { id: 'w-arabic-essentials-8', target: 'عائلة', translation: 'family' },
      { id: 'w-arabic-essentials-9', target: 'صديق', translation: 'friend' },
      { id: 'w-arabic-essentials-10', target: 'محطة', translation: 'station' },
      { id: 'w-arabic-essentials-11', target: 'تذكرة', translation: 'ticket' },
      { id: 'w-arabic-essentials-12', target: 'شارع', translation: 'street' },
      { id: 'w-arabic-essentials-13', target: 'يسار', translation: 'left' },
      { id: 'w-arabic-essentials-14', target: 'يمين', translation: 'right' },
      { id: 'w-arabic-essentials-15', target: 'بكم؟', translation: 'how much?' },
      { id: 'w-arabic-essentials-16', target: 'متجر', translation: 'shop' },
      { id: 'w-arabic-essentials-17', target: 'فندق', translation: 'hotel' },
      { id: 'w-arabic-essentials-18', target: 'صباح', translation: 'morning' },
      { id: 'w-arabic-essentials-19', target: 'مساء', translation: 'evening' },
    ],
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'seed-hindi-basics',
    name: 'Hindi Basics',
    lang: 'hi',
    nativeLang: 'en-US',
    cefr: 'A1',
    words: [
      { id: 'w-hi-namaste', target: 'नमस्ते', translation: 'hello' },
      { id: 'w-hi-dhanyavaad', target: 'धन्यवाद', translation: 'thank you' },
      { id: 'w-hi-kripya', target: 'कृपया', translation: 'please' },
      { id: 'w-hi-haan', target: 'हाँ', translation: 'yes' },
      { id: 'w-hi-alvida', target: 'अलविदा', translation: 'goodbye', repeats: 3 },
      { id: 'w-hindi-basics-5', target: 'नहीं', translation: 'no' },
      { id: 'w-hindi-basics-6', target: 'पानी', translation: 'water' },
      { id: 'w-hindi-basics-7', target: 'रोटी', translation: 'bread' },
      { id: 'w-hindi-basics-8', target: 'परिवार', translation: 'family' },
      { id: 'w-hindi-basics-9', target: 'दोस्त', translation: 'friend' },
      { id: 'w-hindi-basics-10', target: 'स्टेशन', translation: 'station' },
      { id: 'w-hindi-basics-11', target: 'टिकट', translation: 'ticket' },
      { id: 'w-hindi-basics-12', target: 'सड़क', translation: 'street' },
      { id: 'w-hindi-basics-13', target: 'बाएँ', translation: 'left' },
      { id: 'w-hindi-basics-14', target: 'दाएँ', translation: 'right' },
      { id: 'w-hindi-basics-15', target: 'कितने का है?', translation: 'how much?' },
      { id: 'w-hindi-basics-16', target: 'दुकान', translation: 'shop' },
      { id: 'w-hindi-basics-17', target: 'होटल', translation: 'hotel' },
      { id: 'w-hindi-basics-18', target: 'सुबह', translation: 'morning' },
      { id: 'w-hindi-basics-19', target: 'शाम', translation: 'evening' },
    ],
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'seed-turkish-basics',
    name: 'Turkish Basics',
    lang: 'tr',
    nativeLang: 'en-US',
    cefr: 'A1',
    words: [
      { id: 'w-tr-merhaba', target: 'merhaba', translation: 'hello' },
      { id: 'w-tr-tesekkurler', target: 'teşekkürler', translation: 'thank you' },
      { id: 'w-tr-lutfen', target: 'lütfen', translation: 'please' },
      { id: 'w-tr-evet', target: 'evet', translation: 'yes' },
      { id: 'w-tr-hosca-kal', target: 'hoşça kal', translation: 'goodbye', repeats: 3 },
      { id: 'w-turkish-basics-5', target: 'hayır', translation: 'no' },
      { id: 'w-turkish-basics-6', target: 'su', translation: 'water' },
      { id: 'w-turkish-basics-7', target: 'ekmek', translation: 'bread' },
      { id: 'w-turkish-basics-8', target: 'aile', translation: 'family' },
      { id: 'w-turkish-basics-9', target: 'arkadaş', translation: 'friend' },
      { id: 'w-turkish-basics-10', target: 'istasyon', translation: 'station' },
      { id: 'w-turkish-basics-11', target: 'bilet', translation: 'ticket' },
      { id: 'w-turkish-basics-12', target: 'sokak', translation: 'street' },
      { id: 'w-turkish-basics-13', target: 'sol', translation: 'left' },
      { id: 'w-turkish-basics-14', target: 'sağ', translation: 'right' },
      { id: 'w-turkish-basics-15', target: 'ne kadar?', translation: 'how much?' },
      { id: 'w-turkish-basics-16', target: 'dükkân', translation: 'shop' },
      { id: 'w-turkish-basics-17', target: 'otel', translation: 'hotel' },
      { id: 'w-turkish-basics-18', target: 'sabah', translation: 'morning' },
      { id: 'w-turkish-basics-19', target: 'akşam', translation: 'evening' },
    ],
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'seed-persian-basics',
    name: 'Persian Basics',
    lang: 'fa',
    nativeLang: 'en-US',
    cefr: 'A1',
    words: [
      { id: 'w-fa-salam', target: 'سلام', translation: 'hello' },
      { id: 'w-fa-mamnun', target: 'ممنون', translation: 'thank you' },
      { id: 'w-fa-lotfan', target: 'لطفا', translation: 'please' },
      { id: 'w-fa-bale', target: 'بله', translation: 'yes' },
      { id: 'w-fa-khoda-hafez', target: 'خداحافظ', translation: 'goodbye', repeats: 3 },
      { id: 'w-persian-basics-5', target: 'نه', translation: 'no' },
      { id: 'w-persian-basics-6', target: 'آب', translation: 'water' },
      { id: 'w-persian-basics-7', target: 'نان', translation: 'bread' },
      { id: 'w-persian-basics-8', target: 'خانواده', translation: 'family' },
      { id: 'w-persian-basics-9', target: 'دوست', translation: 'friend' },
      { id: 'w-persian-basics-10', target: 'ایستگاه', translation: 'station' },
      { id: 'w-persian-basics-11', target: 'بلیت', translation: 'ticket' },
      { id: 'w-persian-basics-12', target: 'خیابان', translation: 'street' },
      { id: 'w-persian-basics-13', target: 'چپ', translation: 'left' },
      { id: 'w-persian-basics-14', target: 'راست', translation: 'right' },
      { id: 'w-persian-basics-15', target: 'چقدر؟', translation: 'how much?' },
      { id: 'w-persian-basics-16', target: 'فروشگاه', translation: 'shop' },
      { id: 'w-persian-basics-17', target: 'هتل', translation: 'hotel' },
      { id: 'w-persian-basics-18', target: 'صبح', translation: 'morning' },
      { id: 'w-persian-basics-19', target: 'شب', translation: 'evening' },
    ],
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'seed-dutch-basics',
    name: 'Dutch Basics',
    lang: 'nl',
    nativeLang: 'en-US',
    cefr: 'A1',
    words: [
      { id: 'w-nl-hallo', target: 'hallo', translation: 'hello' },
      { id: 'w-nl-dank-je', target: 'dank je', translation: 'thank you' },
      { id: 'w-nl-alsjeblieft', target: 'alsjeblieft', translation: 'please' },
      { id: 'w-nl-ja', target: 'ja', translation: 'yes' },
      { id: 'w-nl-tot-ziens', target: 'tot ziens', translation: 'goodbye', repeats: 3 },
      { id: 'w-dutch-basics-5', target: 'nee', translation: 'no' },
      { id: 'w-dutch-basics-6', target: 'water', translation: 'water' },
      { id: 'w-dutch-basics-7', target: 'brood', translation: 'bread' },
      { id: 'w-dutch-basics-8', target: 'familie', translation: 'family' },
      { id: 'w-dutch-basics-9', target: 'vriend', translation: 'friend' },
      { id: 'w-dutch-basics-10', target: 'station', translation: 'station' },
      { id: 'w-dutch-basics-11', target: 'kaartje', translation: 'ticket' },
      { id: 'w-dutch-basics-12', target: 'straat', translation: 'street' },
      { id: 'w-dutch-basics-13', target: 'links', translation: 'left' },
      { id: 'w-dutch-basics-14', target: 'rechts', translation: 'right' },
      { id: 'w-dutch-basics-15', target: 'hoeveel?', translation: 'how much?' },
      { id: 'w-dutch-basics-16', target: 'winkel', translation: 'shop' },
      { id: 'w-dutch-basics-17', target: 'hotel', translation: 'hotel' },
      { id: 'w-dutch-basics-18', target: 'ochtend', translation: 'morning' },
      { id: 'w-dutch-basics-19', target: 'avond', translation: 'evening' },
    ],
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'seed-swedish-basics',
    name: 'Swedish Basics',
    lang: 'sv',
    nativeLang: 'en-US',
    cefr: 'A1',
    words: [
      { id: 'w-sv-hej', target: 'hej', translation: 'hello / goodbye' },
      { id: 'w-sv-tack', target: 'tack', translation: 'thank you' },
      { id: 'w-sv-snalla', target: 'snälla', translation: 'please' },
      { id: 'w-sv-ja', target: 'ja', translation: 'yes' },
      { id: 'w-sv-hej-da', target: 'hej då', translation: 'goodbye', repeats: 3 },
      { id: 'w-swedish-basics-5', target: 'nej', translation: 'no' },
      { id: 'w-swedish-basics-6', target: 'vatten', translation: 'water' },
      { id: 'w-swedish-basics-7', target: 'bröd', translation: 'bread' },
      { id: 'w-swedish-basics-8', target: 'familj', translation: 'family' },
      { id: 'w-swedish-basics-9', target: 'vän', translation: 'friend' },
      { id: 'w-swedish-basics-10', target: 'station', translation: 'station' },
      { id: 'w-swedish-basics-11', target: 'biljett', translation: 'ticket' },
      { id: 'w-swedish-basics-12', target: 'gata', translation: 'street' },
      { id: 'w-swedish-basics-13', target: 'vänster', translation: 'left' },
      { id: 'w-swedish-basics-14', target: 'höger', translation: 'right' },
      { id: 'w-swedish-basics-15', target: 'hur mycket?', translation: 'how much?' },
      { id: 'w-swedish-basics-16', target: 'butik', translation: 'shop' },
      { id: 'w-swedish-basics-17', target: 'hotell', translation: 'hotel' },
      { id: 'w-swedish-basics-18', target: 'morgon', translation: 'morning' },
      { id: 'w-swedish-basics-19', target: 'kväll', translation: 'evening' },
    ],
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'seed-polish-basics',
    name: 'Polish Basics',
    lang: 'pl',
    nativeLang: 'en-US',
    cefr: 'A1',
    words: [
      { id: 'w-pl-czesc', target: 'cześć', translation: 'hello' },
      { id: 'w-pl-dziekuje', target: 'dziękuję', translation: 'thank you' },
      { id: 'w-pl-prosze', target: 'proszę', translation: 'please / you are welcome', repeats: 3 },
      { id: 'w-pl-tak', target: 'tak', translation: 'yes' },
      { id: 'w-pl-do-widzenia', target: 'do widzenia', translation: 'goodbye' },
      { id: 'w-polish-basics-5', target: 'nie', translation: 'no' },
      { id: 'w-polish-basics-6', target: 'woda', translation: 'water' },
      { id: 'w-polish-basics-7', target: 'chleb', translation: 'bread' },
      { id: 'w-polish-basics-8', target: 'rodzina', translation: 'family' },
      { id: 'w-polish-basics-9', target: 'przyjaciel', translation: 'friend' },
      { id: 'w-polish-basics-10', target: 'stacja', translation: 'station' },
      { id: 'w-polish-basics-11', target: 'bilet', translation: 'ticket' },
      { id: 'w-polish-basics-12', target: 'ulica', translation: 'street' },
      { id: 'w-polish-basics-13', target: 'lewo', translation: 'left' },
      { id: 'w-polish-basics-14', target: 'prawo', translation: 'right' },
      { id: 'w-polish-basics-15', target: 'ile kosztuje?', translation: 'how much?' },
      { id: 'w-polish-basics-16', target: 'sklep', translation: 'shop' },
      { id: 'w-polish-basics-17', target: 'hotel', translation: 'hotel' },
      { id: 'w-polish-basics-18', target: 'rano', translation: 'morning' },
      { id: 'w-polish-basics-19', target: 'wieczór', translation: 'evening' },
    ],
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'seed-greek-basics',
    name: 'Greek Basics',
    lang: 'el',
    nativeLang: 'en-US',
    cefr: 'A1',
    words: [
      { id: 'w-el-geia', target: 'γεια', translation: 'hello' },
      { id: 'w-el-efharisto', target: 'ευχαριστώ', translation: 'thank you' },
      { id: 'w-el-parakalo', target: 'παρακαλώ', translation: 'please / you are welcome', repeats: 3 },
      { id: 'w-el-nai', target: 'ναι', translation: 'yes' },
      { id: 'w-el-antio', target: 'αντίο', translation: 'goodbye' },
      { id: 'w-greek-basics-5', target: 'όχι', translation: 'no' },
      { id: 'w-greek-basics-6', target: 'νερό', translation: 'water' },
      { id: 'w-greek-basics-7', target: 'ψωμί', translation: 'bread' },
      { id: 'w-greek-basics-8', target: 'οικογένεια', translation: 'family' },
      { id: 'w-greek-basics-9', target: 'φίλος', translation: 'friend' },
      { id: 'w-greek-basics-10', target: 'σταθμός', translation: 'station' },
      { id: 'w-greek-basics-11', target: 'εισιτήριο', translation: 'ticket' },
      { id: 'w-greek-basics-12', target: 'δρόμος', translation: 'street' },
      { id: 'w-greek-basics-13', target: 'αριστερά', translation: 'left' },
      { id: 'w-greek-basics-14', target: 'δεξιά', translation: 'right' },
      { id: 'w-greek-basics-15', target: 'πόσο κοστίζει;', translation: 'how much?' },
      { id: 'w-greek-basics-16', target: 'κατάστημα', translation: 'shop' },
      { id: 'w-greek-basics-17', target: 'ξενοδοχείο', translation: 'hotel' },
      { id: 'w-greek-basics-18', target: 'πρωί', translation: 'morning' },
      { id: 'w-greek-basics-19', target: 'βράδυ', translation: 'evening' },
    ],
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'seed-hebrew-basics',
    name: 'Hebrew Basics',
    lang: 'he',
    nativeLang: 'en-US',
    cefr: 'A1',
    words: [
      { id: 'w-he-shalom', target: 'שלום', translation: 'hello' },
      { id: 'w-he-toda', target: 'תודה', translation: 'thank you' },
      { id: 'w-he-bevakasha', target: 'בבקשה', translation: 'please / you are welcome' },
      { id: 'w-he-ken', target: 'כן', translation: 'yes' },
      { id: 'w-he-lehitraot', target: 'להתראות', translation: 'goodbye', repeats: 3 },
      { id: 'w-hebrew-basics-5', target: 'לא', translation: 'no' },
      { id: 'w-hebrew-basics-6', target: 'מים', translation: 'water' },
      { id: 'w-hebrew-basics-7', target: 'לחם', translation: 'bread' },
      { id: 'w-hebrew-basics-8', target: 'משפחה', translation: 'family' },
      { id: 'w-hebrew-basics-9', target: 'חבר', translation: 'friend' },
      { id: 'w-hebrew-basics-10', target: 'תחנה', translation: 'station' },
      { id: 'w-hebrew-basics-11', target: 'כרטיס', translation: 'ticket' },
      { id: 'w-hebrew-basics-12', target: 'רחוב', translation: 'street' },
      { id: 'w-hebrew-basics-13', target: 'שמאל', translation: 'left' },
      { id: 'w-hebrew-basics-14', target: 'ימין', translation: 'right' },
      { id: 'w-hebrew-basics-15', target: 'כמה זה עולה?', translation: 'how much?' },
      { id: 'w-hebrew-basics-16', target: 'חנות', translation: 'shop' },
      { id: 'w-hebrew-basics-17', target: 'מלון', translation: 'hotel' },
      { id: 'w-hebrew-basics-18', target: 'בוקר', translation: 'morning' },
      { id: 'w-hebrew-basics-19', target: 'ערב', translation: 'evening' },
    ],
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'seed-vietnamese-basics',
    name: 'Vietnamese Basics',
    lang: 'vi',
    nativeLang: 'en-US',
    cefr: 'A1',
    words: [
      { id: 'w-vi-xin-chao', target: 'xin chào', translation: 'hello' },
      { id: 'w-vi-cam-on', target: 'cảm ơn', translation: 'thank you' },
      { id: 'w-vi-lam-on', target: 'làm ơn', translation: 'please' },
      { id: 'w-vi-vang', target: 'vâng', translation: 'yes' },
      { id: 'w-vi-tam-biet', target: 'tạm biệt', translation: 'goodbye', repeats: 3 },
      { id: 'w-vietnamese-basics-5', target: 'không', translation: 'no' },
      { id: 'w-vietnamese-basics-6', target: 'nước', translation: 'water' },
      { id: 'w-vietnamese-basics-7', target: 'bánh mì', translation: 'bread' },
      { id: 'w-vietnamese-basics-8', target: 'gia đình', translation: 'family' },
      { id: 'w-vietnamese-basics-9', target: 'bạn', translation: 'friend' },
      { id: 'w-vietnamese-basics-10', target: 'ga', translation: 'station' },
      { id: 'w-vietnamese-basics-11', target: 'vé', translation: 'ticket' },
      { id: 'w-vietnamese-basics-12', target: 'đường', translation: 'street' },
      { id: 'w-vietnamese-basics-13', target: 'trái', translation: 'left' },
      { id: 'w-vietnamese-basics-14', target: 'phải', translation: 'right' },
      { id: 'w-vietnamese-basics-15', target: 'bao nhiêu?', translation: 'how much?' },
      { id: 'w-vietnamese-basics-16', target: 'cửa hàng', translation: 'shop' },
      { id: 'w-vietnamese-basics-17', target: 'khách sạn', translation: 'hotel' },
      { id: 'w-vietnamese-basics-18', target: 'buổi sáng', translation: 'morning' },
      { id: 'w-vietnamese-basics-19', target: 'buổi tối', translation: 'evening' },
    ],
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'seed-thai-basics',
    name: 'Thai Basics',
    lang: 'th',
    nativeLang: 'en-US',
    cefr: 'A1',
    words: [
      { id: 'w-th-sawatdee', target: 'สวัสดี', translation: 'hello' },
      { id: 'w-th-khopkhun', target: 'ขอบคุณ', translation: 'thank you' },
      { id: 'w-th-garuna', target: 'กรุณา', translation: 'please' },
      { id: 'w-th-chai', target: 'ใช่', translation: 'yes' },
      { id: 'w-th-lagon', target: 'ลาก่อน', translation: 'goodbye', repeats: 3 },
      { id: 'w-thai-basics-5', target: 'ไม่', translation: 'no' },
      { id: 'w-thai-basics-6', target: 'น้ำ', translation: 'water' },
      { id: 'w-thai-basics-7', target: 'ขนมปัง', translation: 'bread' },
      { id: 'w-thai-basics-8', target: 'ครอบครัว', translation: 'family' },
      { id: 'w-thai-basics-9', target: 'เพื่อน', translation: 'friend' },
      { id: 'w-thai-basics-10', target: 'สถานี', translation: 'station' },
      { id: 'w-thai-basics-11', target: 'ตั๋ว', translation: 'ticket' },
      { id: 'w-thai-basics-12', target: 'ถนน', translation: 'street' },
      { id: 'w-thai-basics-13', target: 'ซ้าย', translation: 'left' },
      { id: 'w-thai-basics-14', target: 'ขวา', translation: 'right' },
      { id: 'w-thai-basics-15', target: 'เท่าไหร่?', translation: 'how much?' },
      { id: 'w-thai-basics-16', target: 'ร้านค้า', translation: 'shop' },
      { id: 'w-thai-basics-17', target: 'โรงแรม', translation: 'hotel' },
      { id: 'w-thai-basics-18', target: 'เช้า', translation: 'morning' },
      { id: 'w-thai-basics-19', target: 'เย็น', translation: 'evening' },
    ],
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'seed-indonesian-basics',
    name: 'Indonesian Basics',
    lang: 'id',
    nativeLang: 'en-US',
    cefr: 'A1',
    words: [
      { id: 'w-id-halo', target: 'halo', translation: 'hello' },
      { id: 'w-id-terima-kasih', target: 'terima kasih', translation: 'thank you' },
      { id: 'w-id-tolong', target: 'tolong', translation: 'please' },
      { id: 'w-id-ya', target: 'ya', translation: 'yes' },
      { id: 'w-id-selamat-tinggal', target: 'selamat tinggal', translation: 'goodbye', repeats: 3 },
      { id: 'w-indonesian-basics-5', target: 'tidak', translation: 'no' },
      { id: 'w-indonesian-basics-6', target: 'air', translation: 'water' },
      { id: 'w-indonesian-basics-7', target: 'roti', translation: 'bread' },
      { id: 'w-indonesian-basics-8', target: 'keluarga', translation: 'family' },
      { id: 'w-indonesian-basics-9', target: 'teman', translation: 'friend' },
      { id: 'w-indonesian-basics-10', target: 'stasiun', translation: 'station' },
      { id: 'w-indonesian-basics-11', target: 'tiket', translation: 'ticket' },
      { id: 'w-indonesian-basics-12', target: 'jalan', translation: 'street' },
      { id: 'w-indonesian-basics-13', target: 'kiri', translation: 'left' },
      { id: 'w-indonesian-basics-14', target: 'kanan', translation: 'right' },
      { id: 'w-indonesian-basics-15', target: 'berapa?', translation: 'how much?' },
      { id: 'w-indonesian-basics-16', target: 'toko', translation: 'shop' },
      { id: 'w-indonesian-basics-17', target: 'hotel', translation: 'hotel' },
      { id: 'w-indonesian-basics-18', target: 'pagi', translation: 'morning' },
      { id: 'w-indonesian-basics-19', target: 'malam', translation: 'evening' },
    ],
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'seed-swahili-basics',
    name: 'Swahili Basics',
    lang: 'sw',
    nativeLang: 'en-US',
    cefr: 'A1',
    words: [
      { id: 'w-sw-habari', target: 'habari', translation: 'hello / how are you' },
      { id: 'w-sw-asante', target: 'asante', translation: 'thank you' },
      { id: 'w-sw-tafadhali', target: 'tafadhali', translation: 'please' },
      { id: 'w-sw-ndiyo', target: 'ndiyo', translation: 'yes' },
      { id: 'w-sw-kwaheri', target: 'kwaheri', translation: 'goodbye', repeats: 3 },
      { id: 'w-swahili-basics-5', target: 'hapana', translation: 'no' },
      { id: 'w-swahili-basics-6', target: 'maji', translation: 'water' },
      { id: 'w-swahili-basics-7', target: 'mkate', translation: 'bread' },
      { id: 'w-swahili-basics-8', target: 'familia', translation: 'family' },
      { id: 'w-swahili-basics-9', target: 'rafiki', translation: 'friend' },
      { id: 'w-swahili-basics-10', target: 'kituo', translation: 'station' },
      { id: 'w-swahili-basics-11', target: 'tikiti', translation: 'ticket' },
      { id: 'w-swahili-basics-12', target: 'barabara', translation: 'street' },
      { id: 'w-swahili-basics-13', target: 'kushoto', translation: 'left' },
      { id: 'w-swahili-basics-14', target: 'kulia', translation: 'right' },
      { id: 'w-swahili-basics-15', target: 'bei gani?', translation: 'how much?' },
      { id: 'w-swahili-basics-16', target: 'duka', translation: 'shop' },
      { id: 'w-swahili-basics-17', target: 'hoteli', translation: 'hotel' },
      { id: 'w-swahili-basics-18', target: 'asubuhi', translation: 'morning' },
      { id: 'w-swahili-basics-19', target: 'jioni', translation: 'evening' },
    ],
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'seed-ukrainian-basics',
    name: 'Ukrainian Basics',
    lang: 'uk',
    nativeLang: 'en-US',
    cefr: 'A1',
    words: [
      { id: 'w-uk-pryvit', target: 'привіт', translation: 'hello' },
      { id: 'w-uk-dyakuyu', target: 'дякую', translation: 'thank you' },
      { id: 'w-uk-bud-laska', target: 'будь ласка', translation: 'please / you are welcome', repeats: 3 },
      { id: 'w-uk-tak', target: 'так', translation: 'yes' },
      { id: 'w-uk-do-pobachennya', target: 'до побачення', translation: 'goodbye' },
      { id: 'w-ukrainian-basics-5', target: 'ні', translation: 'no' },
      { id: 'w-ukrainian-basics-6', target: 'вода', translation: 'water' },
      { id: 'w-ukrainian-basics-7', target: 'хліб', translation: 'bread' },
      { id: 'w-ukrainian-basics-8', target: 'родина', translation: 'family' },
      { id: 'w-ukrainian-basics-9', target: 'друг', translation: 'friend' },
      { id: 'w-ukrainian-basics-10', target: 'станція', translation: 'station' },
      { id: 'w-ukrainian-basics-11', target: 'квиток', translation: 'ticket' },
      { id: 'w-ukrainian-basics-12', target: 'вулиця', translation: 'street' },
      { id: 'w-ukrainian-basics-13', target: 'ліворуч', translation: 'left' },
      { id: 'w-ukrainian-basics-14', target: 'праворуч', translation: 'right' },
      { id: 'w-ukrainian-basics-15', target: 'скільки коштує?', translation: 'how much?' },
      { id: 'w-ukrainian-basics-16', target: 'магазин', translation: 'shop' },
      { id: 'w-ukrainian-basics-17', target: 'готель', translation: 'hotel' },
      { id: 'w-ukrainian-basics-18', target: 'ранок', translation: 'morning' },
      { id: 'w-ukrainian-basics-19', target: 'вечір', translation: 'evening' },
    ],
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'seed-czech-basics',
    name: 'Czech Basics',
    lang: 'cs',
    nativeLang: 'en-US',
    cefr: 'A1',
    words: [
      { id: 'w-cs-ahoj', target: 'ahoj', translation: 'hello / goodbye' },
      { id: 'w-cs-dekuji', target: 'děkuji', translation: 'thank you' },
      { id: 'w-cs-prosim', target: 'prosím', translation: 'please / you are welcome', repeats: 3 },
      { id: 'w-cs-ano', target: 'ano', translation: 'yes' },
      { id: 'w-cs-na-shledanou', target: 'na shledanou', translation: 'goodbye' },
      { id: 'w-czech-basics-5', target: 'ne', translation: 'no' },
      { id: 'w-czech-basics-6', target: 'voda', translation: 'water' },
      { id: 'w-czech-basics-7', target: 'chléb', translation: 'bread' },
      { id: 'w-czech-basics-8', target: 'rodina', translation: 'family' },
      { id: 'w-czech-basics-9', target: 'přítel', translation: 'friend' },
      { id: 'w-czech-basics-10', target: 'nádraží', translation: 'station' },
      { id: 'w-czech-basics-11', target: 'jízdenka', translation: 'ticket' },
      { id: 'w-czech-basics-12', target: 'ulice', translation: 'street' },
      { id: 'w-czech-basics-13', target: 'vlevo', translation: 'left' },
      { id: 'w-czech-basics-14', target: 'vpravo', translation: 'right' },
      { id: 'w-czech-basics-15', target: 'kolik to stojí?', translation: 'how much?' },
      { id: 'w-czech-basics-16', target: 'obchod', translation: 'shop' },
      { id: 'w-czech-basics-17', target: 'hotel', translation: 'hotel' },
      { id: 'w-czech-basics-18', target: 'ráno', translation: 'morning' },
      { id: 'w-czech-basics-19', target: 'večer', translation: 'evening' },
    ],
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'seed-finnish-basics',
    name: 'Finnish Basics',
    lang: 'fi',
    nativeLang: 'en-US',
    cefr: 'A1',
    words: [
      { id: 'w-fi-hei', target: 'hei', translation: 'hello' },
      { id: 'w-fi-kiitos', target: 'kiitos', translation: 'thank you' },
      { id: 'w-fi-ole-hyva', target: 'ole hyvä', translation: 'please / you are welcome' },
      { id: 'w-fi-kylla', target: 'kyllä', translation: 'yes' },
      { id: 'w-fi-nakemiin', target: 'näkemiin', translation: 'goodbye', repeats: 3 },
      { id: 'w-finnish-basics-5', target: 'ei', translation: 'no' },
      { id: 'w-finnish-basics-6', target: 'vesi', translation: 'water' },
      { id: 'w-finnish-basics-7', target: 'leipä', translation: 'bread' },
      { id: 'w-finnish-basics-8', target: 'perhe', translation: 'family' },
      { id: 'w-finnish-basics-9', target: 'ystävä', translation: 'friend' },
      { id: 'w-finnish-basics-10', target: 'asema', translation: 'station' },
      { id: 'w-finnish-basics-11', target: 'lippu', translation: 'ticket' },
      { id: 'w-finnish-basics-12', target: 'katu', translation: 'street' },
      { id: 'w-finnish-basics-13', target: 'vasen', translation: 'left' },
      { id: 'w-finnish-basics-14', target: 'oikea', translation: 'right' },
      { id: 'w-finnish-basics-15', target: 'paljonko?', translation: 'how much?' },
      { id: 'w-finnish-basics-16', target: 'kauppa', translation: 'shop' },
      { id: 'w-finnish-basics-17', target: 'hotelli', translation: 'hotel' },
      { id: 'w-finnish-basics-18', target: 'aamu', translation: 'morning' },
      { id: 'w-finnish-basics-19', target: 'ilta', translation: 'evening' },
    ],
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'seed-norwegian-basics',
    name: 'Norwegian Basics',
    lang: 'nb-NO',
    nativeLang: 'en-US',
    cefr: 'A1',
    words: [
      { id: 'w-nb-hei', target: 'hei', translation: 'hello' },
      { id: 'w-nb-takk', target: 'takk', translation: 'thank you' },
      { id: 'w-nb-vaer-sa-snill', target: 'vær så snill', translation: 'please' },
      { id: 'w-nb-ja', target: 'ja', translation: 'yes' },
      { id: 'w-nb-ha-det', target: 'ha det', translation: 'goodbye', repeats: 3 },
      { id: 'w-norwegian-basics-5', target: 'nei', translation: 'no' },
      { id: 'w-norwegian-basics-6', target: 'vann', translation: 'water' },
      { id: 'w-norwegian-basics-7', target: 'brød', translation: 'bread' },
      { id: 'w-norwegian-basics-8', target: 'familie', translation: 'family' },
      { id: 'w-norwegian-basics-9', target: 'venn', translation: 'friend' },
      { id: 'w-norwegian-basics-10', target: 'stasjon', translation: 'station' },
      { id: 'w-norwegian-basics-11', target: 'billett', translation: 'ticket' },
      { id: 'w-norwegian-basics-12', target: 'gate', translation: 'street' },
      { id: 'w-norwegian-basics-13', target: 'venstre', translation: 'left' },
      { id: 'w-norwegian-basics-14', target: 'høyre', translation: 'right' },
      { id: 'w-norwegian-basics-15', target: 'hvor mye?', translation: 'how much?' },
      { id: 'w-norwegian-basics-16', target: 'butikk', translation: 'shop' },
      { id: 'w-norwegian-basics-17', target: 'hotell', translation: 'hotel' },
      { id: 'w-norwegian-basics-18', target: 'morgen', translation: 'morning' },
      { id: 'w-norwegian-basics-19', target: 'kveld', translation: 'evening' },
    ],
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'seed-danish-basics',
    name: 'Danish Basics',
    lang: 'da',
    nativeLang: 'en-US',
    cefr: 'A1',
    words: [
      { id: 'w-da-hej', target: 'hej', translation: 'hello' },
      { id: 'w-da-tak', target: 'tak', translation: 'thank you' },
      { id: 'w-da-vaer-sa-venlig', target: 'vær så venlig', translation: 'please' },
      { id: 'w-da-ja', target: 'ja', translation: 'yes' },
      { id: 'w-da-farvel', target: 'farvel', translation: 'goodbye', repeats: 3 },
      { id: 'w-danish-basics-5', target: 'nej', translation: 'no' },
      { id: 'w-danish-basics-6', target: 'vand', translation: 'water' },
      { id: 'w-danish-basics-7', target: 'brød', translation: 'bread' },
      { id: 'w-danish-basics-8', target: 'familie', translation: 'family' },
      { id: 'w-danish-basics-9', target: 'ven', translation: 'friend' },
      { id: 'w-danish-basics-10', target: 'station', translation: 'station' },
      { id: 'w-danish-basics-11', target: 'billet', translation: 'ticket' },
      { id: 'w-danish-basics-12', target: 'gade', translation: 'street' },
      { id: 'w-danish-basics-13', target: 'venstre', translation: 'left' },
      { id: 'w-danish-basics-14', target: 'højre', translation: 'right' },
      { id: 'w-danish-basics-15', target: 'hvor meget?', translation: 'how much?' },
      { id: 'w-danish-basics-16', target: 'butik', translation: 'shop' },
      { id: 'w-danish-basics-17', target: 'hotel', translation: 'hotel' },
      { id: 'w-danish-basics-18', target: 'morgen', translation: 'morning' },
      { id: 'w-danish-basics-19', target: 'aften', translation: 'evening' },
    ],
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'seed-filipino-basics',
    name: 'Filipino Basics',
    lang: 'fil',
    nativeLang: 'en-US',
    cefr: 'A1',
    words: [
      { id: 'w-fil-kumusta', target: 'kumusta', translation: 'hello' },
      { id: 'w-fil-salamat', target: 'salamat', translation: 'thank you' },
      { id: 'w-fil-pakiusap', target: 'pakiusap', translation: 'please' },
      { id: 'w-fil-oo', target: 'oo', translation: 'yes' },
      { id: 'w-fil-paalam', target: 'paalam', translation: 'goodbye', repeats: 3 },
      { id: 'w-filipino-basics-5', target: 'hindi', translation: 'no' },
      { id: 'w-filipino-basics-6', target: 'tubig', translation: 'water' },
      { id: 'w-filipino-basics-7', target: 'tinapay', translation: 'bread' },
      { id: 'w-filipino-basics-8', target: 'pamilya', translation: 'family' },
      { id: 'w-filipino-basics-9', target: 'kaibigan', translation: 'friend' },
      { id: 'w-filipino-basics-10', target: 'istasyon', translation: 'station' },
      { id: 'w-filipino-basics-11', target: 'tiket', translation: 'ticket' },
      { id: 'w-filipino-basics-12', target: 'kalye', translation: 'street' },
      { id: 'w-filipino-basics-13', target: 'kaliwa', translation: 'left' },
      { id: 'w-filipino-basics-14', target: 'kanan', translation: 'right' },
      { id: 'w-filipino-basics-15', target: 'magkano?', translation: 'how much?' },
      { id: 'w-filipino-basics-16', target: 'tindahan', translation: 'shop' },
      { id: 'w-filipino-basics-17', target: 'hotel', translation: 'hotel' },
      { id: 'w-filipino-basics-18', target: 'umaga', translation: 'morning' },
      { id: 'w-filipino-basics-19', target: 'gabi', translation: 'evening' },
    ],
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'seed-mongolian-basics',
    name: 'Mongolian Basics',
    lang: 'mn',
    nativeLang: 'en-US',
    cefr: 'A1',
    words: [
      { id: 'w-mn-sain', target: 'сайн байна уу', translation: 'hello' },
      { id: 'w-mn-bayarlalaa', target: 'баярлалаа', translation: 'thank you', repeats: 3 },
      { id: 'w-mn-guiya', target: 'гуйя', translation: 'please' },
      { id: 'w-mn-tiim', target: 'тийм', translation: 'yes' },
      { id: 'w-mn-ugui', target: 'үгүй', translation: 'no' },
      { id: 'w-mongolian-basics-5', target: 'баяртай', translation: 'goodbye' },
      { id: 'w-mongolian-basics-6', target: 'ус', translation: 'water' },
      { id: 'w-mongolian-basics-7', target: 'талх', translation: 'bread' },
      { id: 'w-mongolian-basics-8', target: 'гэр бүл', translation: 'family' },
      { id: 'w-mongolian-basics-9', target: 'найз', translation: 'friend' },
      { id: 'w-mongolian-basics-10', target: 'буудал', translation: 'station' },
      { id: 'w-mongolian-basics-11', target: 'тасалбар', translation: 'ticket' },
      { id: 'w-mongolian-basics-12', target: 'гудамж', translation: 'street' },
      { id: 'w-mongolian-basics-13', target: 'зүүн', translation: 'left' },
      { id: 'w-mongolian-basics-14', target: 'баруун', translation: 'right' },
      { id: 'w-mongolian-basics-15', target: 'хэд вэ?', translation: 'how much?' },
      { id: 'w-mongolian-basics-16', target: 'дэлгүүр', translation: 'shop' },
      { id: 'w-mongolian-basics-17', target: 'зочид буудал', translation: 'hotel' },
      { id: 'w-mongolian-basics-18', target: 'өглөө', translation: 'morning' },
      { id: 'w-mongolian-basics-19', target: 'орой', translation: 'evening' },
    ],
    createdAt: 0,
    updatedAt: 0,
  },
];
